# Generated by Django 4.0.4 on 2025-11-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(blank=True, help_text='Фото профеля (400x400)', null=True, upload_to='user_image/'),
        ),
    ]
